version: '3'
services:
  app:
    build: .
    container_name: wp-seo
    ports:
      - "8501:8501"
    volumes:
      - ./settings.json:/app/settings.json
      - ./content_hub.sqlite3:/app/content_hub.sqlite3
      - ./secrets:/app/secrets
    restart: unless-stopped
